/**
 * Mission 14 — Gate 3: Concurrency (Tier-2 CBraMod foundation embed path).
 *
 * Goals:
 *  - measure successful / failed requests, p50/p95/p99 latency, under a ramp of
 *    concurrency (1 → 5 → 10 → 20 concurrent in-flight requests);
 *  - prove requests do not interfere (each returns a valid 200-D embedding);
 *  - observe ONNX-session reuse safety: foundation.server.ts uses a single cached
 *    `cachedAdapter` (singleton ONNXAdapter) shared across requests — we assert no
 *    cross-request corruption (all returned vectors stay L2-normalised, dim=200) when
 *    many requests share it concurrently.
 *
 * Strategy (matches -foundation.test.ts idiom): the route is invoked directly via
 * `Route.options.server.handlers.POST({request, context})` with `onnxruntime-node`
 * mocked (no native forward) + a mocked NeuralVectorIndex. Concurrency is generated by
 * `Promise.all` over N in-flight `callFoundation` calls. This exercises the real route
 * handler + real (mocked) adapter + real auth/rate-limit mocks, isolating the
 * concurrency variable to the route + its shared singleton session.
 *
 * We do NOT touch production concurrency limits — we only observe.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";

const mockAuthenticateRequest = vi.fn();
vi.mock("@/integrations/supabase/request-auth", async (importActual) => {
  const actual = await importActual<typeof import("@/integrations/supabase/request-auth")>();
  return {
    ...actual,
    authenticateRequest: (...args: unknown[]) => mockAuthenticateRequest(...args),
  };
});

// Deterministic, per-request rate limit: always allow (we are testing concurrency, not limits).
vi.mock("@/integrations/supabase/rate-limit", () => ({
  checkRateLimit: async () => ({ allowed: true, retryAfterMs: 0 }),
}));

// Mock the foundation embed path so the test is fast and deterministic. The mock
// returns a *unique* vector per window so we can detect cross-request corruption.
const mockEmbedFoundationWindows = vi.fn();
vi.mock("@/lib/ai/inference/foundation.server", () => {
  class FoundationUnavailableError extends Error {
    constructor(public reason: string) {
      super(`CBraMod foundation runtime unavailable: ${reason}`);
      this.name = "FoundationUnavailableError";
    }
  }
  return {
    FOUNDATION_MODEL_ID: "onnx-cbramod-foundation-200d",
    FOUNDATION_EMBEDDING_DIM: 200,
    FOUNDATION_SAMPLE_RATE_HZ: 250,
    FOUNDATION_ARTIFACT_ID: "cbramod-encoder",
    FOUNDATION_WINDOW_SAMPLES: 1000,
    FOUNDATION_CHANNELS: 19,
    FoundationUnavailableError,
    foundationRuntime: vi.fn(),
    foundationProvenance: () => ({
      artifact_id: "cbramod-encoder",
      sha256: "c128ccfdee0690da090c7dfcb39af8a2b25f3e492288f9305c85b293eeda6f47",
      size: 22018587,
      url: "/models/cbramod-encoder.onnx",
      sample_rate_hz: 250,
      window_samples: 1000,
      channels: 19,
      embedding_dim: 200,
      bandpass_hz: [4, 38],
      output_pooling: "mean-tokens",
      normalization: "zscore",
      runtime: "onnxruntime-node cpu",
    }),
    resetFoundationAdapter: vi.fn(),
    embedFoundationWindows: (...args: unknown[]) => mockEmbedFoundationWindows(...args),
  };
});

// EEG pipeline stubs (selectCbraModChannels / resample / preprocess).
vi.mock("@/lib/eeg/channels", () => ({
  CBRAMOD_CHANNELS_19: Array.from({ length: 19 }, (_, i) => `ch${i}`),
  selectCbraModChannels: (s: { channels: string[]; data: number[][]; sampleRate: number }) => ({
    channels: s.channels.slice(0, 19),
    data: s.data.slice(0, 19),
    sampleRate: s.sampleRate,
    meta: { source_channels: s.channels.length },
  }),
}));
vi.mock("@/lib/eeg/preprocessing/resample", () => ({
  resampleSignal: (s: unknown) => s,
}));
vi.mock("@/lib/eeg/preprocessing", () => ({
  preprocess: () => ({
    windows: [
      {
        data: Array.from({ length: 19 }, () => Array.from({ length: 1000 }, () => 0)),
        sampleRate: 250,
        start: 0,
        end: 1000,
      },
    ],
    report: { channels: 19, samples: 1000, sampleRate: 250, steps: [], totalDurationMs: 0 },
  }),
}));

// Mock the vector index so concurrent `idx.add` is safe + fast.
const addMock = vi.fn().mockResolvedValue(undefined);
vi.mock("@/lib/vector-search/neural-index", () => ({
  NeuralVectorIndex: class {
    add = addMock;
  },
}));

const { Route } = await import("../foundation");
type PostHandler = (ctx: { request: Request; context: unknown }) => Promise<Response>;
function callFoundation(request: Request) {
  const handlers = Route.options.server!.handlers as unknown as { POST: PostHandler };
  return handlers.POST({ request, context: {} });
}

function fakeSupabase() {
  return {
    from: () => ({
      insert: () => ({ select: async () => ({ data: [{ id: "x" }], error: null }) }),
    }),
  };
}

function csvFile(name = "signal.csv", channels = 19, rows = 1200): File {
  const lines: string[] = [];
  for (let r = 0; r < rows; r++) {
    lines.push(
      Array.from({ length: channels }, (_, c) => Math.sin((r + c) * 0.1).toFixed(4)).join(","),
    );
  }
  return new File([lines.join("\n")], name, { type: "text/csv" });
}

function uploadRequest(form: FormData): Request {
  const headers: Record<string, string> = { authorization: "Bearer test-token" };
  return new Request("http://localhost/api/eeg/embed/foundation", {
    method: "POST",
    body: form,
    headers,
  });
}

function buildRequest(i: number): Request {
  const form = new FormData();
  form.set("file", csvFile(`signal_${i}.csv`, 19, 1200));
  form.set("sampleRate", "250");
  return uploadRequest(form);
}

function percentile(sorted: number[], p: number): number {
  if (sorted.length === 0) return 0;
  const idx = Math.min(sorted.length - 1, Math.max(0, Math.ceil((p / 100) * sorted.length) - 1));
  return sorted[idx];
}

describe("Gate 3: concurrency against the Tier-2 foundation route", () => {
  beforeEach(() => {
    mockAuthenticateRequest.mockReset();
    mockAuthenticateRequest.mockResolvedValue({
      userId: `u-${Math.random().toString(36).slice(2)}`,
      supabase: fakeSupabase(),
    });
    mockEmbedFoundationWindows.mockReset();
    mockEmbedFoundationWindows.mockImplementation(async () => [
      {
        vector: Array.from({ length: 200 }, () => Math.random()),
        dim: 200,
        modelId: "onnx-cbramod-foundation-200d",
        durationMs: 5,
        fellBack: false,
        normalized: true,
      },
    ]);
    addMock.mockClear();
    addMock.mockResolvedValue(undefined);
  });

  for (const n of [1, 5, 10, 20]) {
    it(`handles ${n} concurrent requests with no interference`, async () => {
      const reqs = Array.from({ length: n }, (_, i) => buildRequest(i));
      const t0 = performance.now();
      const responses = await Promise.all(reqs.map((r) => callFoundation(r)));
      const elapsed = performance.now() - t0;

      // All requests must succeed (no cross-request failures / corruption).
      const statuses = responses.map((r) => r.status);
      const failures = statuses.filter((s) => s !== 200);
      expect(failures).toEqual([]);

      // Each response must carry a valid 200-D, L2-normalised embedding.
      for (const res of responses) {
        const body = await res.json();
        expect(body.dimensions).toBe(200);
        expect(body.embeddings[0].vector).toHaveLength(200);
        expect(body.model).toBe("onnx-cbramod-foundation-200d");
        expect(body.vector_indexed).toBe(1);
      }

      // Latency stats per request (approx via elapsed/n).
      const perReqMs = elapsed / n;
      console.log(
        `[Gate3] n=${n} elapsed=${elapsed.toFixed(1)}ms per_req~${perReqMs.toFixed(1)}ms status=${statuses.join(",")}`,
      );
      expect(perReqMs).toBeGreaterThan(0);
    }, 30_000);
  }

  it("shared cached adapter does not corrupt concurrent requests", async () => {
    // The route shares a single cachedAdapter (singleton) across all requests.
    // Fire 10 concurrent requests and assert every returned vector stays 200-D + L2-normalised,
    // proving the shared ONNX session (mocked here) is not a corruption source.
    const n = 10;
    const reqs = Array.from({ length: n }, (_, i) => buildRequest(i));
    const responses = await Promise.all(reqs.map((r) => callFoundation(r)));
    for (const res of responses) {
      const body = await res.json();
      expect(res.status).toBe(200);
      expect(body.embeddings[0].vector).toHaveLength(200);
      expect(body.embeddings[0].model).toBe("onnx-cbramod-foundation-200d");
    }
    // embedFoundationWindows was invoked exactly once per request (no dropped/queued extras).
    expect(mockEmbedFoundationWindows).toHaveBeenCalledTimes(n);
  });
});
