/**
 * T-006 — Pyodide-MNE preprocessing parity harness.
 *
 * Compares the TS `bandpass`, `notch`, and `segment` implementations against
 * gold-standard reference outputs produced by MNE-Python (see
 * `scripts/generate_mne_parity_fixtures.py`). The gold file is a .npz
 * containing the MNE-filtered version of the same deterministic synthetic
 * signal the TS code processes here.
 *
 * If the gold file is not present (MNE not installed), the parity
 * assertions are skipped with a clear message rather than failing — the
 * remaining structural tests still run.
 *
 * Tolerance: MNE's IIR filtfilt and our biquad filtfilt use the same
 * cookbook design but differ slightly in numerical precision. We assert
 * correlation ≥ 0.999 and mean-absolute-error ≤ 0.5 µV, which is tight
 * enough to catch implementation bugs but tolerant of float32 roundoff.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { bandpass, notch } from "../filters";
import { segment } from "../segment";

// --- Deterministic synthetic signal (must match generate_mne_parity_fixtures.py) ---
const FS = 250;
const N = 1000;
const N_CHAN = 4;
// Simple LCG seeded with 42 to match numpy's default_rng(42) is infeasible
// in pure TS; instead we use a hash-based PRNG. The *parity* check uses the
// golden file, which was generated with the numpy RNG. For the structural
// tests (non-parity), we just need *a* deterministic signal.
function syntheticSignal(): number[][] {
  let state = 42;
  const rng = () => {
    // xorshift32
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return ((state >>> 0) / 0xffffffff - 0.5) * 0.2; // ±0.1 µV noise
  };
  const data: number[][] = [];
  for (let ch = 0; ch < N_CHAN; ch++) {
    const row = new Array<number>(N);
    for (let i = 0; i < N; i++) {
      const t = i / FS;
      row[i] =
        Math.sin(2 * Math.PI * 10 * t + ch * 0.5) * 50.0 +
        Math.sin(2 * Math.PI * 50 * t) * 5.0 +
        rng();
    }
    data.push(row);
  }
  return data;
}

// --- Gold file loader ---
const GOLDEN_PATH = join(process.cwd(), "training", "cache", "parity", "mne_golden.npz");

interface Gold {
  raw: Float32Array;
  bandpass: Float32Array;
  notch: Float32Array;
  segments: Float32Array;
  fs: number;
  channels: number;
  windowSamples: number;
  step: number;
}

function loadGold(): Gold | null {
  if (!existsSync(GOLDEN_PATH)) {
    console.log("Gold file does not exist at:", GOLDEN_PATH);
    return null;
  }
  const buf = readFileSync(GOLDEN_PATH);
  console.log("Gold file size:", buf.length);
  // Minimal NPZ parser: NPZ is a ZIP of .npy files. We use a basic unzip.
  // For the parity harness, the gold file is generated by the Python
  // script; in CI we only run the structural tests if it's absent.
  // (Full NPZ parsing is handled by the npy parser in parsers/npy.ts for
  // arrays, but NPZ is a zip — we delegate to a tiny inline unzip.)
  return parseNpz(buf);
}

/** Minimal NPZ (ZIP) reader that extracts .npy arrays into Float32Arrays.
 * Assumes no compression (stored only), which matches np.savez output. */
function parseNpz(buf: Buffer): Gold | null {
  // NPZ is a ZIP archive. We look for the stored .npy entries.
  // This is a minimal implementation sufficient for the gold file.
  try {
    const map: Record<string, Float32Array | number> = {};
    let pos = 0;
    while (pos < buf.length - 4) {
      // Local file header signature: PK\x03\x04
      if (
        buf[pos] === 0x50 &&
        buf[pos + 1] === 0x4b &&
        buf[pos + 2] === 0x03 &&
        buf[pos + 3] === 0x04
      ) {
        const nameLen = buf.readUInt16LE(pos + 26);
        const extraLen = buf.readUInt16LE(pos + 28);
        const compMethod = buf.readUInt16LE(pos + 28);
        const compSize = buf.readUInt32LE(pos + 18);
        const name = buf.toString("ascii", pos + 30, pos + 30 + nameLen).replace(/\.npy$/, "");
        const dataStart = pos + 30 + nameLen + extraLen;
        const compressed = buf.subarray(dataStart, dataStart + compSize);

        // We only handle stored (no compression) entries.
        if (compMethod !== 0) {
          // Skip this entry (should not happen for our file).
          pos = dataStart + compSize;
          continue;
        }

        const npy = parseNpy(compressed);
        if (npy !== null) {
          map[name] = npy;
        }

        // Move to next potential header
        pos = dataStart + compSize;
      } else {
        pos++;
      }
    }

    if (
      map.raw &&
      map.bandpass &&
      map.notch &&
      map.fs !== undefined &&
      map.channels !== undefined &&
      map.windowSamples !== undefined &&
      map.step !== undefined
    ) {
      return {
        raw: map.raw as Float32Array,
        bandpass: map.bandpass as Float32Array,
        notch: map.notch as Float32Array,
        segments: (map.segments as Float32Array) ?? new Float32Array(0),
        fs: (map.fs as number) ?? FS,
        channels: (map.channels as number) ?? N_CHAN,
        windowSamples: (map.windowSamples as number) ?? FS * 2,
        step: (map.step as number) ?? (FS * 2) / 2,
      };
    }
    return null;
  } catch {
    return null;
  }
}

/** Minimal .npy parser for float32 arrays. */
function parseNpy(buf: Buffer): Float32Array | number | null {
  if (buf[0] !== 0x93) return null; // numpy magic
  // Header: magic (6) + version (2) + header_len (2 or 4) + header
  const headerLen = buf.readUInt16LE(8);
  const header = buf.toString("latin1", 10, 10 + headerLen);
  // Parse shape and dtype from the header dict string.
  const shapeMatch = header.match(/'shape':\s*\(([^)]*)\)/);
  const dtypeMatch = header.match(/'descr':\s*'([^']*)'/);
  if (!shapeMatch || !dtypeMatch) return null;
  const shape = shapeMatch[1].split(",").map((s) => parseInt(s.trim(), 10));
  const dtype = dtypeMatch[1];
  const dataStart = 10 + headerLen;
  const data = buf.subarray(dataStart);

  // Scalar (fs, channels, etc.) — shape is () or (1,)
  if (shape.length === 0 || (shape.length === 1 && shape[0] <= 1)) {
    if (dtype.includes("i")) return data.readInt32LE(0);
    if (dtype.includes("f")) return data.readFloatLE(0);
    return null;
  }

  // Array — return as flat Float32Array (caller reshapes by known dims)
  if (dtype.includes("f4")) {
    return new Float32Array(data.buffer, data.byteOffset, data.byteLength / 4);
  }
  return null;
}

// --- Tests ---

describe("T-006 Pyodide-MNE parity harness", () => {
  const gold = loadGold();

  describe("structural correctness (always runs)", () => {
    it("bandpass preserves signal dimensions", () => {
      const sig = syntheticSignal();
      const out = bandpass(sig, FS, 8, 30);
      expect(out).toHaveLength(N_CHAN);
      expect(out[0]).toHaveLength(N);
    });

    it("notch preserves signal dimensions", () => {
      const sig = syntheticSignal();
      const out = notch(sig, FS, 50);
      expect(out).toHaveLength(N_CHAN);
      expect(out[0]).toHaveLength(N);
    });

    it("segment produces correct window count and overlap", () => {
      const sig = syntheticSignal();
      const windows = segment(sig, FS, 2, 0.5);
      const W = FS * 2;
      const step = Math.floor(W * 0.5);
      const expected = Math.floor((N - W) / step) + 1;
      expect(windows).toHaveLength(expected);
      expect(windows[0].data).toHaveLength(N_CHAN);
      expect(windows[0].data[0]).toHaveLength(W);
    });

    it("bandpass attenuates out-of-band components (50 Hz mains removed)", () => {
      const sig = syntheticSignal();
      const out = bandpass(sig, FS, 8, 30);
      // The 50 Hz component should be heavily attenuated. Measure power
      // reduction in the 45-55 Hz band via a crude FFT magnitude check.
      const inBandPower = spectralPower(sig[0], FS, 45, 55);
      const outBandPower = spectralPower(out[0], FS, 45, 55);
      expect(outBandPower).toBeLessThan(inBandPower * 0.1);
    });

    it("notch attenuates the 50 Hz component specifically", () => {
      const sig = syntheticSignal();
      const out = notch(sig, FS, 50);
      const before = spectralPower(sig[0], FS, 48, 52);
      const after = spectralPower(out[0], FS, 48, 52);
      expect(after).toBeLessThan(before * 0.2);
    });
  });

  describe("MNE gold-file parity (runs if gold available)", () => {
    const it_gold = gold ? it : it.skip;
    const g = gold as Gold;

    it_gold("TS bandpass matches MNE bandpass within tolerance", () => {
      const sig = reshape(g.raw, g.channels, N);
      const tsOut = bandpass(sig, g.fs, 8, 30);
      const mneOut = reshape(g.bandpass, g.channels, N);
      const { corr, mae } = compareArrays(tsOut, mneOut);
      expect(corr).toBeGreaterThanOrEqual(0.999);
      expect(mae).toBeLessThan(0.5);
    });

    it_gold("TS notch matches MNE notch within tolerance", () => {
      const sig = reshape(g.raw, g.channels, N);
      const tsOut = notch(sig, g.fs, 50);
      const mneOut = reshape(g.notch, g.channels, N);
      const { corr, mae } = compareArrays(tsOut, mneOut);
      expect(corr).toBeGreaterThanOrEqual(0.999);
      expect(mae).toBeLessThan(0.5);
    });
  });
});

// --- Helpers ---

/** Reshape a flat Float32Array to [C][N] (row-major). */
function reshape(flat: Float32Array, c: number, n: number): number[][] {
  const out: number[][] = [];
  for (let ch = 0; ch < c; ch++) {
    const row = new Array<number>(n);
    for (let i = 0; i < n; i++) row[i] = flat[ch * n + i];
    out.push(row);
  }
  return out;
}

/** Crude spectral power in a band via DFT magnitude squared. */
function spectralPower(x: number[], fs: number, lo: number, hi: number): number {
  const n = x.length;
  let power = 0;
  let count = 0;
  for (let k = 0; k < n / 2; k++) {
    const freq = (k * fs) / n;
    if (freq >= lo && freq <= hi) {
      let re = 0,
        im = 0;
      for (let i = 0; i < n; i++) {
        const angle = (2 * Math.PI * k * i) / n;
        re += x[i] * Math.cos(angle);
        im -= x[i] * Math.sin(angle);
      }
      power += (re * re + im * im) / (n * n);
      count++;
    }
  }
  return count > 0 ? power / count : 0;
}

/** Pearson correlation and mean absolute error between two [C][N] arrays. */
function compareArrays(a: number[][], b: number[][]): { corr: number; mae: number } {
  let sumA = 0,
    sumB = 0,
    sumAB = 0,
    sumA2 = 0,
    sumB2 = 0,
    absDiff = 0,
    count = 0;
  for (let ch = 0; ch < a.length; ch++) {
    for (let i = 0; i < a[ch].length; i++) {
      const av = a[ch][i];
      const bv = b[ch][i];
      sumA += av;
      sumB += bv;
      sumAB += av * bv;
      sumA2 += av * av;
      sumB2 += bv * bv;
      absDiff += Math.abs(av - bv);
      count++;
    }
  }
  const meanA = sumA / count;
  const meanB = sumB / count;
  const cov = sumAB / count - meanA * meanB;
  const stdA = Math.sqrt(sumA2 / count - meanA * meanA);
  const stdB = Math.sqrt(sumB2 / count - meanB * meanB);
  const corr = cov / (stdA * stdB || 1);
  const mae = absDiff / count;
  return { corr, mae };
}
