/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyntheticRouteImport } from './routes/synthetic'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as EmbeddingsRouteImport } from './routes/embeddings'
import { Route as Eeg2imageRouteImport } from './routes/eeg2image'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedOnnxRouteImport } from './routes/_authenticated/onnx'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedMneRouteImport } from './routes/_authenticated/mne'
import { Route as AuthenticatedExperimentsRouteImport } from './routes/_authenticated/experiments'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiEegUploadRouteImport } from './routes/api/eeg/upload'
import { Route as AuthenticatedDashboardResearcherRouteImport } from './routes/_authenticated/dashboard.researcher'
import { Route as AuthenticatedDashboardIndividualRouteImport } from './routes/_authenticated/dashboard.individual'
import { Route as AuthenticatedDashboardEnterpriseRouteImport } from './routes/_authenticated/dashboard.enterprise'
import { Route as AuthenticatedDashboardAnalysesRouteImport } from './routes/_authenticated/dashboard.analyses'

const SyntheticRoute = SyntheticRouteImport.update({
  id: '/synthetic',
  path: '/synthetic',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddingsRoute = EmbeddingsRouteImport.update({
  id: '/embeddings',
  path: '/embeddings',
  getParentRoute: () => rootRouteImport,
} as any)
const Eeg2imageRoute = Eeg2imageRouteImport.update({
  id: '/eeg2image',
  path: '/eeg2image',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnnxRoute = AuthenticatedOnnxRouteImport.update({
  id: '/onnx',
  path: '/onnx',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMneRoute = AuthenticatedMneRouteImport.update({
  id: '/mne',
  path: '/mne',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperimentsRoute =
  AuthenticatedExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiEegUploadRoute = ApiEegUploadRouteImport.update({
  id: '/api/eeg/upload',
  path: '/api/eeg/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardResearcherRoute =
  AuthenticatedDashboardResearcherRouteImport.update({
    id: '/researcher',
    path: '/researcher',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIndividualRoute =
  AuthenticatedDashboardIndividualRouteImport.update({
    id: '/individual',
    path: '/individual',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEnterpriseRoute =
  AuthenticatedDashboardEnterpriseRouteImport.update({
    id: '/enterprise',
    path: '/enterprise',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalysesRoute =
  AuthenticatedDashboardAnalysesRouteImport.update({
    id: '/analyses',
    path: '/analyses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/developers': typeof DevelopersRoute
  '/eeg2image': typeof Eeg2imageRoute
  '/embeddings': typeof EmbeddingsRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/synthetic': typeof SyntheticRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/mne': typeof AuthenticatedMneRoute
  '/models': typeof AuthenticatedModelsRoute
  '/onnx': typeof AuthenticatedOnnxRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/dashboard/analyses': typeof AuthenticatedDashboardAnalysesRoute
  '/dashboard/enterprise': typeof AuthenticatedDashboardEnterpriseRoute
  '/dashboard/individual': typeof AuthenticatedDashboardIndividualRoute
  '/dashboard/researcher': typeof AuthenticatedDashboardResearcherRoute
  '/api/eeg/upload': typeof ApiEegUploadRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/developers': typeof DevelopersRoute
  '/eeg2image': typeof Eeg2imageRoute
  '/embeddings': typeof EmbeddingsRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/synthetic': typeof SyntheticRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/mne': typeof AuthenticatedMneRoute
  '/models': typeof AuthenticatedModelsRoute
  '/onnx': typeof AuthenticatedOnnxRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/dashboard/analyses': typeof AuthenticatedDashboardAnalysesRoute
  '/dashboard/enterprise': typeof AuthenticatedDashboardEnterpriseRoute
  '/dashboard/individual': typeof AuthenticatedDashboardIndividualRoute
  '/dashboard/researcher': typeof AuthenticatedDashboardResearcherRoute
  '/api/eeg/upload': typeof ApiEegUploadRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/developers': typeof DevelopersRoute
  '/eeg2image': typeof Eeg2imageRoute
  '/embeddings': typeof EmbeddingsRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/synthetic': typeof SyntheticRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/experiments': typeof AuthenticatedExperimentsRoute
  '/_authenticated/mne': typeof AuthenticatedMneRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/onnx': typeof AuthenticatedOnnxRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/dashboard/analyses': typeof AuthenticatedDashboardAnalysesRoute
  '/_authenticated/dashboard/enterprise': typeof AuthenticatedDashboardEnterpriseRoute
  '/_authenticated/dashboard/individual': typeof AuthenticatedDashboardIndividualRoute
  '/_authenticated/dashboard/researcher': typeof AuthenticatedDashboardResearcherRoute
  '/api/eeg/upload': typeof ApiEegUploadRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architecture'
    | '/developers'
    | '/eeg2image'
    | '/embeddings'
    | '/playground'
    | '/pricing'
    | '/research'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/studio'
    | '/synthetic'
    | '/dashboard'
    | '/datasets'
    | '/experiments'
    | '/mne'
    | '/models'
    | '/onnx'
    | '/training'
    | '/upload'
    | '/dashboard/analyses'
    | '/dashboard/enterprise'
    | '/dashboard/individual'
    | '/dashboard/researcher'
    | '/api/eeg/upload'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/architecture'
    | '/developers'
    | '/eeg2image'
    | '/embeddings'
    | '/playground'
    | '/pricing'
    | '/research'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/studio'
    | '/synthetic'
    | '/datasets'
    | '/experiments'
    | '/mne'
    | '/models'
    | '/onnx'
    | '/training'
    | '/upload'
    | '/dashboard/analyses'
    | '/dashboard/enterprise'
    | '/dashboard/individual'
    | '/dashboard/researcher'
    | '/api/eeg/upload'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/architecture'
    | '/developers'
    | '/eeg2image'
    | '/embeddings'
    | '/playground'
    | '/pricing'
    | '/research'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/studio'
    | '/synthetic'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/experiments'
    | '/_authenticated/mne'
    | '/_authenticated/models'
    | '/_authenticated/onnx'
    | '/_authenticated/training'
    | '/_authenticated/upload'
    | '/_authenticated/dashboard/analyses'
    | '/_authenticated/dashboard/enterprise'
    | '/_authenticated/dashboard/individual'
    | '/_authenticated/dashboard/researcher'
    | '/api/eeg/upload'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DevelopersRoute: typeof DevelopersRoute
  Eeg2imageRoute: typeof Eeg2imageRoute
  EmbeddingsRoute: typeof EmbeddingsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PricingRoute: typeof PricingRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  SyntheticRoute: typeof SyntheticRoute
  ApiEegUploadRoute: typeof ApiEegUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/synthetic': {
      id: '/synthetic'
      path: '/synthetic'
      fullPath: '/synthetic'
      preLoaderRoute: typeof SyntheticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embeddings': {
      id: '/embeddings'
      path: '/embeddings'
      fullPath: '/embeddings'
      preLoaderRoute: typeof EmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eeg2image': {
      id: '/eeg2image'
      path: '/eeg2image'
      fullPath: '/eeg2image'
      preLoaderRoute: typeof Eeg2imageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onnx': {
      id: '/_authenticated/onnx'
      path: '/onnx'
      fullPath: '/onnx'
      preLoaderRoute: typeof AuthenticatedOnnxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mne': {
      id: '/_authenticated/mne'
      path: '/mne'
      fullPath: '/mne'
      preLoaderRoute: typeof AuthenticatedMneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments': {
      id: '/_authenticated/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AuthenticatedExperimentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/eeg/upload': {
      id: '/api/eeg/upload'
      path: '/api/eeg/upload'
      fullPath: '/api/eeg/upload'
      preLoaderRoute: typeof ApiEegUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/researcher': {
      id: '/_authenticated/dashboard/researcher'
      path: '/researcher'
      fullPath: '/dashboard/researcher'
      preLoaderRoute: typeof AuthenticatedDashboardResearcherRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/individual': {
      id: '/_authenticated/dashboard/individual'
      path: '/individual'
      fullPath: '/dashboard/individual'
      preLoaderRoute: typeof AuthenticatedDashboardIndividualRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/enterprise': {
      id: '/_authenticated/dashboard/enterprise'
      path: '/enterprise'
      fullPath: '/dashboard/enterprise'
      preLoaderRoute: typeof AuthenticatedDashboardEnterpriseRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analyses': {
      id: '/_authenticated/dashboard/analyses'
      path: '/analyses'
      fullPath: '/dashboard/analyses'
      preLoaderRoute: typeof AuthenticatedDashboardAnalysesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnalysesRoute: typeof AuthenticatedDashboardAnalysesRoute
  AuthenticatedDashboardEnterpriseRoute: typeof AuthenticatedDashboardEnterpriseRoute
  AuthenticatedDashboardIndividualRoute: typeof AuthenticatedDashboardIndividualRoute
  AuthenticatedDashboardResearcherRoute: typeof AuthenticatedDashboardResearcherRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnalysesRoute: AuthenticatedDashboardAnalysesRoute,
    AuthenticatedDashboardEnterpriseRoute:
      AuthenticatedDashboardEnterpriseRoute,
    AuthenticatedDashboardIndividualRoute:
      AuthenticatedDashboardIndividualRoute,
    AuthenticatedDashboardResearcherRoute:
      AuthenticatedDashboardResearcherRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedExperimentsRoute: typeof AuthenticatedExperimentsRoute
  AuthenticatedMneRoute: typeof AuthenticatedMneRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedOnnxRoute: typeof AuthenticatedOnnxRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedExperimentsRoute: AuthenticatedExperimentsRoute,
  AuthenticatedMneRoute: AuthenticatedMneRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedOnnxRoute: AuthenticatedOnnxRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArchitectureRoute: ArchitectureRoute,
  DevelopersRoute: DevelopersRoute,
  Eeg2imageRoute: Eeg2imageRoute,
  EmbeddingsRoute: EmbeddingsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PricingRoute: PricingRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  SyntheticRoute: SyntheticRoute,
  ApiEegUploadRoute: ApiEegUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
